name: CI Tests

on:
  - pull_request
  - push

env:
  CI: true

jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 8.x
          - 10.x
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache npm
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}

      - run: npm install
      
      - name: "Set up Cloud credentials"
        run: |
          echo ${{ secrets.service_account_json_base64 }} | base64 -d > ./scripts/service-account.json
          export GOOGLE_APPLICATION_CREDENTIALS="./scripts/service-account.json"
          export GCLOUD_PROJECT="firestore-snippets"
      
      - run: ./scripts/test.sh